const students=[{
    "id": 1,
    "first_name": "Gery",
    "last_name": "Peach",
    "email": "gpeach0@over-blog.com",
    "gender": "Male",
    "ip_address": "174.246.203.194"
  }, {
    "id": 2,
    "first_name": "Marcelline",
    "last_name": "Tale",
    "email": "mtale1@geocities.com",
    "gender": "Genderfluid",
    "ip_address": "157.240.30.53"
  }, {
    "id": 3,
    "first_name": "Carin",
    "last_name": "BURWIN",
    "email": "cburwin2@tamu.edu",
    "gender": "Agender",
    "ip_address": "221.90.26.159"
  }, {
    "id": 4,
    "first_name": "Hew",
    "last_name": "Glede",
    "email": "hglede3@oakley.com",
    "gender": "Genderqueer",
    "ip_address": "29.216.52.80"
  }, {
    "id": 5,
    "first_name": "Ches",
    "last_name": "Piscopello",
    "email": "cpiscopello4@github.io",
    "gender": "Polygender",
    "ip_address": "22.187.73.19"
  }, {
    "id": 6,
    "first_name": "Quintina",
    "last_name": "Tottle",
    "email": "qtottle5@diigo.com",
    "gender": "Female",
    "ip_address": "244.242.254.17"
  }, {
    "id": 7,
    "first_name": "Othello",
    "last_name": "Bloom",
    "email": "obloom6@answers.com",
    "gender": "Agender",
    "ip_address": "11.128.232.158"
  }, {
    "id": 8,
    "first_name": "Stirling",
    "last_name": "Mutter",
    "email": "smutter7@ucla.edu",
    "gender": "Agender",
    "ip_address": "181.206.50.144"
  }, {
    "id": 9,
    "first_name": "Nicolea",
    "last_name": "Rutt",
    "email": "nrutt8@uol.com.br",
    "gender": "Genderqueer",
    "ip_address": "255.117.200.27"
  }, {
    "id": 10,
    "first_name": "Lorena",
    "last_name": "Brixey",
    "email": "lbrixey9@pen.io",
    "gender": "Genderfluid",
    "ip_address": "26.250.39.190"
  }]



module.exports=students